{% set name = "introspection" %}
{% set version = "1.9.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/introspection-{{ version }}.tar.gz
  sha256: a0090c7b9f6e1907cd73459cf36d14543920991f0cb92799bff265f9e030c921

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}
    - ordered-set
    - renumerate
    - sentinel
    - typing_extensions

test:
  imports:
    - introspection
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Aran-Fey/introspection
  doc_url: https://aran-fey.github.io/introspection/build/html/index.html
  summary: New and improved introspection functions
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
